micronaut:
  application:
    name: fretesGrpc
  server:
    port: 8083

grpc:
  server:
    health:
      enabled: true

endpoints:
  all:
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

